### PR TITLE
Initial sketch - take 2

### PR DESCRIPTION
**Pull request by taphu**
See commits for comments.

### CODE REVIEW

**Comment by taphu** [comment]
@glasserc I updated this quite substantially. One major thing I did was git rid of a lot of type-level abstraction. For instance, users of the library can't define their own state type. The state is always an opaque `ByteString`. Same with keys. Keys are always `Key` now. Also, I got rid of the `weight` concept. The goal right now is to get an MVP that uses luck (aka, probability) to ensure that the keyspace is evenly distributed among the nodes, and assumes that the keyspace is populated uniformly.

**Comment by glasserc** [comment]
OK, this looks OK to me. But it still seems like this framework is somewhat limited to just doing basic key-value stuff. There's no way to access enough of the persistence layer to serve a request like "Get me the the oldest key" or anything like that. Is that by design?

**Comment by taphu** [comment]
I'm not sure what "basic key-value" means to you, but I think maybe some
examples will help. The idea is that the key (as defined by the framework)
is similar to DynamoDB's hash key. The "values" that the key can take on
can be *any sort of state at all*. For instance, the "state" could be a
sqlite database, and the requests could be sql commands to run on that
database.

Or the key could identify different queues, which are encoded in the state
value, and the requests could be operations on those queues.

The purpose is not to specifically to provide a framework for key-value
stores. The purpose is to provide a framework that can act as a container
for *any* type of servcie that can be partitioned.

Looking at it from a different perspective, yes you are correct. The
framework itself is essentially just a key-value store (at this point,
anyway), but the operations on those values are user-defined.

There are also a number of ways that the framework itself could be
extended. For instance, giving the user-defined request logic a handle on
the framework's request handling mechanism itself would allow the request
logic to perform knock-on requests that could, for instance, implement
joins with other keys.

But the first step is mainly just to generalize cluster management and
rebalancing.



On Fri, Jul 3, 2015 at 9:13 PM, Ethan Glasser-Camp <notifications@github.com

**Comment by taphu** [comment]
Another for-instance: A DynamoDB-like range key (and local indexing) could be implemented by making the key state be just another self-contained key-value store.

**Pull request merged**
